# Generated by Django 5.2.7 on 2025-11-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='weather',
        ),
        migrations.AddField(
            model_name='entry',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', '😊'), ('sad', '😢'), ('excited', '🤩'), ('anxious', '😰'), ('calm', '😌'), ('neutral', '😐')], max_length=20),
        ),
        migrations.AddField(
            model_name='entry',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
